# Install Pytorch

url:　https://pytorch.org/get-started/locally/

In [1]:
import torch as t
print(t.__version__)

1.12.1


# Create Tensor

In [2]:
import torch as t
import numpy as np
a = t.Tensor([[1,2,3],[4,5,6]])
a_numpy = a.numpy()
a_list = a.tolist()
b = np.array([[3,2,1],[1,2,3]])
a_tensorf= t.from_numpy(b)
print(a)
print(a.numel())
print(a_numpy)
print(a_list)
print(a_tensorf)

tensor([[1., 2., 3.],
        [4., 5., 6.]])
6
[[1. 2. 3.]
 [4. 5. 6.]]
[[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]]
tensor([[3, 2, 1],
        [1, 2, 3]], dtype=torch.int32)


In [1]:
import torch as t
x1 = t.zeros(3,2)
x2 = t.ones(4,3)
x3 = t.arange(1, 6)
x4 = t.linspace(0, 10, 5)
x5 = t.randn(2, 3)
x6 = t.randperm(5) 
x7 = t.eye(2, 3)
print('x1: {}'.format(x1.numpy()))
print('x2: {}'.format(x2.numpy()))
print('x3: {}'.format(x3.numpy()))
print('x4: {}'.format(x4.numpy()))
print('x5: {}'.format(x5.numpy()))
print('x6: {}'.format(x6.numpy()))
print('x7: {}'.format(x7.numpy()))

x1: [[0. 0.]
 [0. 0.]
 [0. 0.]]
x2: [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
x3: [1 2 3 4 5]
x4: [ 0.   2.5  5.   7.5 10. ]
x5: [[ 1.3090683   1.2123877   0.929149  ]
 [-0.0933357   0.05030454 -1.4430957 ]]
x6: [2 3 1 0 4]
x7: [[1. 0. 0.]
 [0. 1. 0.]]


# Basic Operation

In [5]:
import torch as t
x = t.Tensor([[12,15],[3,4]])
y = t.Tensor([[5,6],[7,8]])
sum_num = x + y
sub_num = x - y
mul_num = x * y
div_num = x / y
mod_num = x % y
neg_num = -x
print('sum_num:\n {}'.format(sum_num.numpy()))
print('sub_num:\n {}'.format(sub_num.numpy()))
print('mul_num:\n {}'.format(mul_num.numpy()))
print('div_num:\n {}'.format(div_num.numpy()))
print('mod_num:\n {}'.format(mod_num.numpy()))
print('neg_num:\n {}'.format(neg_num.numpy()))

sum_num:
 [[17. 21.]
 [10. 12.]]
sub_num:
 [[ 7.  9.]
 [-4. -4.]]
mul_num:
 [[60. 90.]
 [21. 32.]]
div_num:
 [[2.4        2.5       ]
 [0.42857143 0.5       ]]
mod_num:
 [[2. 3.]
 [3. 4.]]
neg_num:
 [[-12. -15.]
 [ -3.  -4.]]


In [ ]:
import torch as t
x = t.Tensor([[12,15],[3,4]])
y = t.Tensor([[5,6],[7,8]])
sum_num = t.add(x, y)
sub_num = t.subtract(x, y)
mul_num = t.multiply(x, y)
div_num = t.divide(x, y)
mod_num = t.remainder(x,y)
neg_num = t.negative(x)
print('sum_num: {}'.format(sum_num.numpy()))
print('sub_num: {}'.format(sub_num.numpy()))
print('mul_num: {}'.format(mul_num.numpy()))
print('div_num: {}'.format(div_num.numpy()))
print('mod_num: {}'.format(mod_num.numpy()))
print('neg_num: {}'.format(neg_num.numpy()))

# Matrix Operation

In [8]:
import torch as t
x1 = t.randn(2, 3)
x2 = t.randn(3, 3)
print(f'x1=\n {x1}')
print(f'x2=\n {x2}')
matrix_product = t.mm(x1, x2)  # matrix multiplication
matrix_inv = t.inverse(x2) 
matrix_trans = t.transpose(x1,0, 1)
print(matrix_product)
print(matrix_inv)
print(matrix_trans)

x1=
 tensor([[-1.1364,  0.9651,  0.0121],
        [-0.6928, -2.0345,  0.1941]])
x2=
 tensor([[-0.4150,  0.6183,  1.8645],
        [-1.2161,  0.2591, -0.4610],
        [ 1.9124,  0.6431, -0.0709]])
tensor([[-0.6790, -0.4447, -2.5645],
        [ 3.1328, -0.8307, -0.3677]])
tensor([[-0.0898, -0.4015,  0.2481],
        [ 0.3126,  1.1423,  0.7942],
        [ 0.4127, -0.4682, -0.2081]])
tensor([[-1.1364, -0.6928],
        [ 0.9651, -2.0345],
        [ 0.0121,  0.1941]])


# Tensor Type  


| Data type                | dtype                             | CPU tensor                                                   | GPU tensor                |
| ------------------------ | --------------------------------- | ------------------------------------------------------------ | ------------------------- |
| 32-bit floating point    | `torch.float32` or `torch.float`  | `torch.FloatTensor`                                          | `torch.cuda.FloatTensor`  |
| 64-bit floating point    | `torch.float64` or `torch.double` | `torch.DoubleTensor`                                         | `torch.cuda.DoubleTensor` |
| 16-bit floating point    | `torch.float16` or `torch.half`   | `torch.HalfTensor`                                           | `torch.cuda.HalfTensor`   |
| 8-bit integer (unsigned) | `torch.uint8`                     | [`torch.ByteTensor`](https://pytorch.org/docs/stable/tensors.html#torch.ByteTensor) | `torch.cuda.ByteTensor`   |
| 8-bit integer (signed)   | `torch.int8`                      | `torch.CharTensor`                                           | `torch.cuda.CharTensor`   |
| 16-bit integer (signed)  | `torch.int16` or `torch.short`    | `torch.ShortTensor`                                          | `torch.cuda.ShortTensor`  |
| 32-bit integer (signed)  | `torch.int32` or `torch.int`      | `torch.IntTensor`                                            | `torch.cuda.IntTensor`    |
| 64-bit integer (signed)  | `torch.int64` or `torch.long`     | `torch.LongTensor`                                           | `torch.cuda.LongTensor`   |
  
FloatTensor ->  'float32'  

DoubleTensor -> 'float64'  

ShortTensor -> 'int16'  

IntTensor -> 'int32'  

LongTensor -> 'int64'  

In [9]:
a = t.Tensor([[1,2,3],[4,5,6]])
print(a.dtype)
a_double = a.double()   #'float64'
print(a_double.dtype)
a_int = a.int()      #'int32'
print(a_int.dtype)

torch.float32
torch.float64
torch.int32


# Common Function

In [3]:
import torch as t
x = t.Tensor([[12,-15],[3,4]])
print(f'x =\n {x}')
print(t.sum(x))
print(t.mean(x))
print(t.min(x))
print(t.max(x))
print(t.abs(x))
print('======')
print(t.sum(x, dim=0))
print(t.mean(x, dim=0))

x =
 tensor([[ 12., -15.],
        [  3.,   4.]])
tensor(4.)
tensor(1.)
tensor(-15.)
tensor(12.)
tensor([[12., 15.],
        [ 3.,  4.]])
tensor([ 15., -11.])
tensor([ 7.5000, -5.5000])


In [12]:
x = t.Tensor([[1.1, 2.2, 3.3],[4.5, 3.2, 2.1], [5, 0, -2]])
print('x =\n',x)
print(t.argmax(x, dim=0))  # get index
print(t.argmin(x, dim=0))
print(t.argmax(x, dim=1))
print(t.argmin(x, dim=1))

x =
 tensor([[ 1.1000,  2.2000,  3.3000],
        [ 4.5000,  3.2000,  2.1000],
        [ 5.0000,  0.0000, -2.0000]])
tensor([2, 1, 0])
tensor([0, 2, 2])
tensor([2, 0, 0])
tensor([0, 2, 2])


# Random 

In [13]:
import torch as t
a=t.randint(0,3,(3,2))
b=t.rand(3)
c=t.rand(3,2,dtype=t.double)
d=t.randn(4,3,dtype=t.double)
print(a,a.dtype)
print(b,b.dtype)
print(c,c.dtype)
print(d,d.dtype)

tensor([[1, 1],
        [2, 0],
        [1, 2]]) torch.int64
tensor([0.9434, 0.8514, 0.6429]) torch.float32
tensor([[0.1072, 0.4693],
        [0.2529, 0.4887],
        [0.9906, 0.2374]], dtype=torch.float64) torch.float64
tensor([[-0.2176,  2.4810, -1.1562],
        [-0.3127,  0.9646,  1.9424],
        [-1.6356,  0.3337, -0.6960],
        [ 1.6346, -0.5955,  0.8764]], dtype=torch.float64) torch.float64


# index and slicing

In [14]:
x = t.Tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(x[0,0])
print(x[0,1])
print(x[1,:])
print(x[:,2])

tensor(1.)
tensor(2.)
tensor([4., 5., 6.])
tensor([3., 6., 9.])


# reshape & flatten

In [16]:
# 1. permute 用法: 列換行
# import torch
# x = torch.randn(2, 3, 5) 
# print(x)
# print(x.size() )
# print('x.permute(2, 0, 1)=\n',x.permute(2, 0, 1))  # permute shape change  torch.Size([5, 2, 3])
# x.permute(2, 0, 1).size() 

# 2. reshape (沒限制)& view(只能用在contiguous nunber): view is reshape function
import torch
x = torch.randn(3, 4)
print(x.shape)
x=x.permute(1,0)  # permute 會變成非连续的情况
print(x.shape)
print('x=\n',x)
print(x.is_contiguous())

# 非连续的情况下使用.view和.reshape:
print(x.reshape(3,4))
# print(x.view(3,4)) # RuntimeError:
x=x.contiguous()
print(x.is_contiguous())
x=x.view(1,12)
print('=========================')
print('x.view(1,12)=',x)

# 3. resize_ 
x = torch.tensor([[1, 2], [3, 4], [5, 6]])
print('x=\n',x)
x.resize_(2, 2)
print('x.reshape(2, 2)=\n',x)

torch.Size([3, 4])
torch.Size([4, 3])
x=
 tensor([[-0.5173, -1.5020, -0.5148],
        [-1.1729,  0.4186,  1.3047],
        [-1.2549,  0.1275,  0.8942],
        [-0.1548,  0.9036, -0.1140]])
False
tensor([[-0.5173, -1.5020, -0.5148, -1.1729],
        [ 0.4186,  1.3047, -1.2549,  0.1275],
        [ 0.8942, -0.1548,  0.9036, -0.1140]])
True
x.view(1,12)= tensor([[-0.5173, -1.5020, -0.5148, -1.1729,  0.4186,  1.3047, -1.2549,  0.1275,
          0.8942, -0.1548,  0.9036, -0.1140]])
x=
 tensor([[1, 2],
        [3, 4],
        [5, 6]])
x.reshape(2, 2)=
 tensor([[1, 2],
        [3, 4]])


In [16]:
import torch as t
x =  t.Tensor([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,1]])
print('x=\n',x)
print('x.shape=',x.shape)
print('x.reshape([2,6]=',x.reshape([2,6]))
print('x.reshape([2,-1]=',x.reshape([2,-1]))
print('(x.reshape([2,3,-1])=,'x.reshape([2,3,-1]))  # 
# view V.S. reshape
# ref: https://www.codenong.com/cs105381089/
print('==========')
print(x.view([2,6]))
print(x.view([2,-1]))
print(x.view([2,3,-1]))
print('==========')
print(x.flatten()) # change 1D Data

torch.Size([3, 4])
tensor([[ 1.,  2.,  3.,  4.,  5.,  6.],
        [ 7.,  8.,  9., 10., 11.,  1.]])
tensor([[ 1.,  2.,  3.,  4.,  5.,  6.],
        [ 7.,  8.,  9., 10., 11.,  1.]])
tensor([[[ 1.,  2.],
         [ 3.,  4.],
         [ 5.,  6.]],

        [[ 7.,  8.],
         [ 9., 10.],
         [11.,  1.]]])
tensor([[ 1.,  2.,  3.,  4.,  5.,  6.],
        [ 7.,  8.,  9., 10., 11.,  1.]])
tensor([[ 1.,  2.,  3.,  4.,  5.,  6.],
        [ 7.,  8.,  9., 10., 11.,  1.]])
tensor([[[ 1.,  2.],
         [ 3.,  4.],
         [ 5.,  6.]],

        [[ 7.,  8.],
         [ 9., 10.],
         [11.,  1.]]])
tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.,  1.])


# Squeeze & Unsqueeze

In [17]:
x = t.Tensor([1,2,3,4,5,6])
y = x.unsqueeze(dim=0)  # 0 axis add 1D
z = x.unsqueeze(dim=1)  # 1 axis add 1D
print(x.shape,'\n',x)
print(y.shape,'\n',y)
print(z.shape,'\n',z)
print('=====================')
x = t.Tensor([[[1,2,3],[4,5,6]]])
print(x.shape)
y = x.squeeze(dim=0)   # shape 中 數字1的壓縮掉(維度=1 且被指定到的Axis 才壓，不是1不能壓)
w = x.squeeze(dim=1)   # 不能壓
z = x.squeeze(dim=2)   # 不能壓
print('x=',x.shape,'\n',x)
print('y=',y.shape,'\n',y)
print('w=',w.shape,'\n',w)
print('z=',z.shape,'\n',z)

# 維度不斷提高
x = t.Tensor([1,2,3,4,5,6])
test = x.unsqueeze(dim=0).unsqueeze(dim=0).unsqueeze(dim=0)
print('y shape= ',test.shape)

torch.Size([6]) 
 tensor([1., 2., 3., 4., 5., 6.])
torch.Size([1, 6]) 
 tensor([[1., 2., 3., 4., 5., 6.]])
torch.Size([6, 1]) 
 tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.]])
torch.Size([1, 2, 3])
x= torch.Size([1, 2, 3]) 
 tensor([[[1., 2., 3.],
         [4., 5., 6.]]])
y= torch.Size([2, 3]) 
 tensor([[1., 2., 3.],
        [4., 5., 6.]])
w= torch.Size([1, 2, 3]) 
 tensor([[[1., 2., 3.],
         [4., 5., 6.]]])
z= torch.Size([1, 2, 3]) 
 tensor([[[1., 2., 3.],
         [4., 5., 6.]]])
y shape=  torch.Size([1, 1, 1, 6])


# Activation Function  
![activation](./images/activation.png)

In [25]:
x = t.Tensor([[1,-2,3],[-4,5,6]])
sig_result = t.sigmoid(x)
tanh_result = t.tanh(x)
relu_result = t.relu(x)
print(sig_result)
print(tanh_result)
print(relu_result)

tensor([[0.7311, 0.1192, 0.9526],
        [0.0180, 0.9933, 0.9975]])
tensor([[ 0.7616, -0.9640,  0.9951],
        [-0.9993,  0.9999,  1.0000]])
tensor([[1., 0., 3.],
        [0., 5., 6.]])


# 重要: *** Dataset/DataLoader  
 
- `__getitem__`：返回一個數據樣本(`obj[index]`等價於`obj.__getitem__(index)`)
- `__len__`：返回樣本的數量(`len(obj)`等價於`obj.__len__()`)    

In [18]:
import torch
from torch.utils.data import Dataset, DataLoader, TensorDataset
BATCH_SIZE = 5
x = torch.linspace(1, 10, 10)
y = torch.linspace(11, 20, 10)
print(x)
print(y)
torch_dataset = TensorDataset(x, y)  # 將x, y 轉換成 tensor shuffle ,batch ...
# num_workers=0 不用多核心CPU
loader = DataLoader(dataset=torch_dataset, batch_size=BATCH_SIZE, shuffle=True, num_workers=0 )
for epoch in range(10):
    for step, (batch_x, batch_y) in enumerate(loader):
        print('Epoch: ', epoch, '| Step: ', step, '| batch x: ', batch_x.numpy(), '| batch y: ', batch_y.numpy())

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])
tensor([11., 12., 13., 14., 15., 16., 17., 18., 19., 20.])
Epoch:  0 | Step:  0 | batch x:  [ 7.  8.  4.  3. 10.] | batch y:  [17. 18. 14. 13. 20.]
Epoch:  0 | Step:  1 | batch x:  [1. 2. 6. 5. 9.] | batch y:  [11. 12. 16. 15. 19.]
Epoch:  1 | Step:  0 | batch x:  [ 1. 10.  3.  6.  4.] | batch y:  [11. 20. 13. 16. 14.]
Epoch:  1 | Step:  1 | batch x:  [8. 7. 9. 2. 5.] | batch y:  [18. 17. 19. 12. 15.]
Epoch:  2 | Step:  0 | batch x:  [ 9.  3. 10.  6.  4.] | batch y:  [19. 13. 20. 16. 14.]
Epoch:  2 | Step:  1 | batch x:  [5. 1. 8. 2. 7.] | batch y:  [15. 11. 18. 12. 17.]
Epoch:  3 | Step:  0 | batch x:  [ 7.  9.  6. 10.  5.] | batch y:  [17. 19. 16. 20. 15.]
Epoch:  3 | Step:  1 | batch x:  [8. 3. 2. 4. 1.] | batch y:  [18. 13. 12. 14. 11.]
Epoch:  4 | Step:  0 | batch x:  [ 7.  8.  5.  6. 10.] | batch y:  [17. 18. 15. 16. 20.]
Epoch:  4 | Step:  1 | batch x:  [1. 4. 2. 3. 9.] | batch y:  [11. 14. 12. 13. 19.]
Epoch:  5 | Step:

In [19]:
# use Dataset for Class 必填 : def __getitem__(self, index): &  def __len__(self):
import os
import numpy as np
import pandas as pd
from torch.utils.data import Dataset, DataLoader
class Mydataset(Dataset):
    def __init__(self):  # load Dataset & 區分x, y & normalization
        """
        return a single data and a corresponding single label
        """
        df = pd.read_csv('pima-indians-diabetes.csv')  # 糖尿病dataset 
        print(df.head(10))
        print("===================================================")
        self.labels = df['label']
        self.dataset = df.drop('label', axis=1)
        self.labels = np.asarray(self.labels)
        self.dataset = np.asarray(self.dataset)
        #print(self.labels[:5])        
        #print(self.dataset[:5])
        ## add normalization to here if you want
    def __getitem__(self, index):
        """
        return a single data and a corresponding single label
        """
        return self.dataset[index], self.labels[index] # 規定一定要寫 return 當筆的Dataset & labels
    def __len__(self):
        """
        return total data length
        """
        return len(self.dataset)  # 規定一定要寫 return total data length
my_data = Mydataset()
data, label = my_data[0]
#print(data)
#print(label)
for data, label in my_data:
    print(data)
    print(label)
    print('===================')

'''
for data, label in my_data:
    print(data)
    print(label)
    print('===')
'''
my_data_loader = DataLoader(my_data, batch_size=5, shuffle=True)
for batch_data, batch_labels in my_data_loader:
    print(batch_data.shape)
    print(batch_labels.shape)
    print(batch_data)
    print(batch_labels)
    break

   pregnant  glucose  bp  skin  insulin   bmi  pedigree  age  label
0         6      148  72    35        0  33.6     0.627   50      1
1         1       85  66    29        0  26.6     0.351   31      0
2         8      183  64     0        0  23.3     0.672   32      1
3         1       89  66    23       94  28.1     0.167   21      0
4         0      137  40    35      168  43.1     2.288   33      1
5         5      116  74     0        0  25.6     0.201   30      0
6         3       78  50    32       88  31.0     0.248   26      1
7        10      115   0     0        0  35.3     0.134   29      0
8         2      197  70    45      543  30.5     0.158   53      1
9         8      125  96     0        0   0.0     0.232   54      1
[  6.    148.     72.     35.      0.     33.6     0.627  50.   ]
1
[ 1.    85.    66.    29.     0.    26.6    0.351 31.   ]
0
[  8.    183.     64.      0.      0.     23.3     0.672  32.   ]
1
[ 1.    89.    66.    23.    94.    28.1    0.167 21.   

# Gradient

In [33]:
import torch
x = torch.ones((1,))  # 沒有在宣告時設 requires_grad=True 不能微分
print(x.requires_grad)

x = torch.ones((1,), requires_grad=True)
print(x.requires_grad)  # 宣告時設 requires_grad=True 可微分

y = torch.zeros((1,))   
print(y.requires_grad)
 
z = 2*x + y  # x 可微分, y不能微分 ，x+y 可微分
print(z.requires_grad)

y.requires_grad_(True) # y 經設定後可微分
print(y.requires_grad)

False
True
False
True
True


In [20]:
import torch
x = torch.ones((1,), requires_grad=True)  #  requires_grad=True -> x 可微分
y = 2*x*x - x + 3
y.backward()   # y 的式子被微分
print(x.grad)  # 針對x 微分

tensor([3.])


In [21]:
import torch
x = torch.Tensor([[1,2,3],[4,5,6]])
x.requires_grad_(True)
y = 2*x*x - x + 3
y.backward(torch.ones(2,3)) # y 的式子被微分
print(y)
print(x.grad)   # # 針對x 微分 : x list 中每個元素帶入: 

tensor([[ 4.,  9., 18.],
        [31., 48., 69.]], grad_fn=<AddBackward0>)
tensor([[ 3.,  7., 11.],
        [15., 19., 23.]])


In [36]:
import torch
x = torch.Tensor([[1,2,3],[4,5,6]])
x.requires_grad_(True)
y = 2*x*x - x + 3
y.backward(torch.ones(2,3)+1)
print(x.grad)
# y 對 x 微分 =  4x -1 : 將x 的值帶入 get :[[3, 7, 11],  * [[1+1, 1+1, 1+1],
#                                         [15,19,23]]      [1+1, 1+1, 1+1]
# result: tensor([[ 6., 14., 22.],
#                [30., 38., 46.]])

tensor([[ 6., 14., 22.],
        [30., 38., 46.]])


$$
y = x^2\bullet e^x
$$

$$
{dy \over dx} = 2x\bullet e^x + x^2 \bullet e^x
$$

In [38]:
def f(x):
    y = x**2 * t.exp(x)
    return y
def gradf(x): 
    dx = 2*x*t.exp(x) + x**2*t.exp(x)
    return dx

x = t.randn(3,4, requires_grad = True)
y = f(x)
# y 式子微分 ,放大倍率一倍 : y 式子對x 微分 後的結果 * t.ones(y.size()這個矩陣
y.backward(t.ones(y.size()))  
print(x.grad)       # 對x 微分
print(gradf(x)) 

tensor([[ 4.1232e-01,  1.6449e+01,  1.4099e+00,  1.5436e+01],
        [ 6.3995e+00, -4.6112e-01,  2.1490e-02, -2.0558e-01],
        [-5.4392e-02, -1.4111e-02,  2.7715e+00,  4.6422e+00]])
tensor([[ 4.1232e-01,  1.6449e+01,  1.4099e+00,  1.5436e+01],
        [ 6.3995e+00, -4.6112e-01,  2.1490e-02, -2.0558e-01],
        [-5.4392e-02, -1.4111e-02,  2.7715e+00,  4.6422e+00]],
       grad_fn=<AddBackward0>)


# Optimization 

In [41]:
learning_rate = 0.1
x = torch.ones((1,), requires_grad=True)
print('x=',x)
optimizer = torch.optim.SGD([x], lr=learning_rate)
#optimizer = torch.optim.RMSprop([x], lr=learning_rate, alpha=0.9)
#optimizer = torch.optim.Adam([x], lr=learning_rate, betas=(0.9, 0.99))
for i in range(1000):
    y = 2*x*x-x+3
    optimizer.zero_grad()
    y.backward()
    optimizer.step()
print(x)
# print(x.numpy()) # error : 可以微分的數值, 不能直接轉Numpy，必須用 detach().numpy()
print(x.detach().numpy()) # 

tensor([0.2500], requires_grad=True)
[0.25000003]
