### Module 18:  unbind使用 
#### unbind at axis = 0
![Alt text](./images/basic_tensorflow/unstack_axis0.png)
#### unbind at axis = 1
![Alt text](./images/basic_tensorflow/unstack_axis1.png)
#### unbind at axis = 2
![Alt text](./images/basic_tensorflow/unstack_axis2.png)


In [1]:
import torch
x = torch.tensor([[0.7,0.9],[0.1,0.4],[0.5,0.8]])
print(x.shape)
axis0_x = torch.unbind(x, dim=0)
print(axis0_x[0])
print(axis0_x[1])
print(axis0_x[2])
axis1_x = torch.unbind(x, dim=1)
print(axis1_x[0])
print(axis1_x[1])
torch.unbind(torch.tensor([[1, 2, 3],
                           [4, 5, 6],
                           [7, 8, 9]]))

torch.Size([3, 2])
tensor([0.7000, 0.9000])
tensor([0.1000, 0.4000])
tensor([0.5000, 0.8000])
tensor([0.7000, 0.1000, 0.5000])
tensor([0.9000, 0.4000, 0.8000])


(tensor([1, 2, 3]), tensor([4, 5, 6]), tensor([7, 8, 9]))

### stack使用
#### origin data
![Alt text](./images/basic_tensorflow/stack_origin.png)
#### stack at axis = 0
![Alt text](./images/basic_tensorflow/stack_axis0.png)
#### stack at axis = 1
![Alt text](./images/basic_tensorflow/stack_axis1.png)

In [4]:
import torch
x = torch.tensor([[1.0, 2.0], [3.0, 4.0], [5.0, 6.0]])
y = torch.tensor([[1.0, 1.0], [0.0, 1.0], [1.0, 1.0]])
print('x.shape = ',x.shape)
print('y.shape = ',y.shape)
stacked_axis0_result = torch.stack([x,y], axis=0)
stacked_axis1_result = torch.stack([x,y], axis=1)
stacked_axis2_result = torch.stack([x,y], axis=2)
print('0=============================') 
print(stacked_axis0_result)
print(stacked_axis0_result.shape)
print('1=============================')    
print(stacked_axis1_result)
print(stacked_axis1_result.shape)
print('2=============================')
print(stacked_axis2_result)
print(stacked_axis2_result.shape)

x.shape =  torch.Size([3, 2])
y.shape =  torch.Size([3, 2])
0=============================
tensor([[[1., 2.],
         [3., 4.],
         [5., 6.]],

        [[1., 1.],
         [0., 1.],
         [1., 1.]]])
torch.Size([2, 3, 2])
1=============================
tensor([[[1., 2.],
         [1., 1.]],

        [[3., 4.],
         [0., 1.]],

        [[5., 6.],
         [1., 1.]]])
torch.Size([3, 2, 2])
2=============================
tensor([[[1., 1.],
         [2., 1.]],

        [[3., 0.],
         [4., 1.]],

        [[5., 1.],
         [6., 1.]]])
torch.Size([3, 2, 2])
