# 將資料做Z-score normalization 

In [ ]:
import torch
import matplotlib.pyplot as plt
# pytorch -> 跟 numpy 指令一樣
rand_data = torch.randint(10,100,(100,2)).float()
print(rand_data.shape)
print(rand_data)

In [ ]:
plt.figure()
plt.plot(rand_data[:, 0].numpy(),rand_data[:, 1].numpy(),"y*") # y is yellow color
# rand_data[:, 0] , 矩陣第1位置是Data 總數，矩陣第2位置 0 表示第1欄 ，當x，矩陣第2位置1  當y

In [ ]:
# pytorch 跟 numpy 一 樣，容易做矩陣運算
#將rand_data做Z-score normalization  = (X -平均值)/標準差
norm_data = (rand_data - rand_data.mean(dim=0)) / rand_data.std(dim=0)
print(norm_data )
plt.figure()
plt.plot(norm_data[:, 0].numpy(), norm_data[:, 1].numpy(),"r.")

# 計算兩個向量曼哈頓距離

In [ ]:
# 曼哈頓距離 : d(x,y)=|x1-x2|+|y1-y2|
import torch
vector1 =  torch.Tensor([1,6,3])
vector2 = torch.Tensor([2,4,5])

diff = vector1 - vector2
print(diff)
abs_tensor = torch.abs(diff)
print(abs_tensor)
manhattan_dist = torch.sum(abs_tensor)

print('manhattan_dist is: {}'.format(manhattan_dist))

# 寫一個one-hot函數來產生one-hot編碼

In [2]:
import torch
def one_hot(num, totol_length):
    return torch.eye(totol_length)[num]

print(one_hot(2,3))
print(one_hot(0,10))
print(one_hot(3,10))

tensor([0., 0., 1.])
tensor([1., 0., 0., 0., 0., 0., 0., 0., 0., 0.])
tensor([0., 0., 0., 1., 0., 0., 0., 0., 0., 0.])


In [3]:
print(torch.eye(3))
print('====================')
print(torch.eye(3)[0])
print('====================')
print(torch.eye(3)[1])
print('====================')
print(torch.eye(3)[2])

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
tensor([1., 0., 0.])
tensor([0., 1., 0.])
tensor([0., 0., 1.])


# 優化以下函數(假設x, y ,z 初始值均為1, learning_rate = 0.1)  
$$
f = x^2+y^2+z^2+ 2x+4y-6z
$$

In [ ]:
import torch
learning_rate = 0.1
x = torch.ones((1,), requires_grad=True)
y = torch.ones((1,), requires_grad=True)
z = torch.ones((1,), requires_grad=True)


optimizer = torch.optim.SGD([x, y, z], lr=learning_rate)


for i in range(100):
    f = x*x + y*y+ z*z + 2*x+ 4*y - 6*z
    optimizer.zero_grad()
    f.backward()
    optimizer.step()

print('when x={}, y={}, z={},  f have min value {}'.format(x.detach().numpy(), y.detach().numpy(), z.detach().numpy(), f.detach().numpy()))