# MSE

In [4]:
import torch
import torch.nn as nn
import numpy as np
import math
#MSE Loss
x = torch.Tensor([1,2,3])
target = torch.Tensor([2,2,3])
criterion = nn.MSELoss()
loss = criterion(x,target)
print(loss)
print(loss.item())

tensor(0.3333)
0.3333333432674408


# Cross-Entropy

In [5]:
import torch
import torch.nn as nn
import numpy as np
import math

predict = torch.Tensor([[0.1,0.5,0.4],[0.1,0.1,0.8]])
label = torch.LongTensor([1,2])
loss = nn.CrossEntropyLoss(reduction="none")
print(loss(predict,label))
loss = nn.CrossEntropyLoss(reduction="mean")
print(loss(predict,label))
loss = nn.CrossEntropyLoss(reduction="sum")
print(loss(predict,label))

tensor([0.9459, 0.6897])
tensor(0.8178)
tensor(1.6356)


## Define Cost

In [16]:
import torch
from torchvision.datasets import mnist
from torch.utils.data import DataLoader
import numpy as np
import torch.nn.functional as F
# Get cpu or gpu device for training.
device = "cuda" if torch.cuda.is_available() else "cpu"
print("Using {} device".format(device))
def data_transform(x):
    x = np.array(x, dtype = 'float32') / 255
    x = x.reshape((-1, ))
    x = torch.from_numpy(x)
    return x
trainset = mnist.MNIST('./dataset/mnist', train=True, transform=data_transform, download=True)
testset = mnist.MNIST('./dataset/mnist', train = False, transform=data_transform, download=True)

train_data = DataLoader(trainset, batch_size=64, shuffle=True)
test_data = DataLoader(testset, batch_size=128, shuffle=False)
class DNN(nn.Module):
    def __init__(self):
        super(DNN, self).__init__()
        self.fc1 = nn.Linear(28*28, 500)
        self.fc2 = nn.Linear(500, 250)
        self.fc3 = nn.Linear(250, 125)
        self.fc4 = nn.Linear(125, 10)
    def forward(self, x):
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = F.relu(self.fc3(x))
        x = self.fc4(x)
        return x
# build model
model = DNN().to(device)
criterion1 = nn.CrossEntropyLoss(reduction="none") # reduction="none"，各自算各自的
criterion2 = nn.CrossEntropyLoss()
model.train()
pred = model(trainset.data[0:5].reshape(-1,784).float())
# Calculate loss
loss = criterion1(pred, trainset.targets[0:5])
print(loss.detach().numpy())
avg_loss = criterion2(pred, trainset.targets[0:5])
print(avg_loss.item())

Using cpu device
[ 4.758217  13.291159   1.1667422  1.2169385  4.660825 ]
5.018775939941406


In [15]:
a = torch.tensor([1.,2.,3.], requires_grad = True)# float 才能計算梯度
print(a.grad)
out = a.sigmoid()
print(out)

out.sum().backward()  # 必須加backward() 才能計算梯度
print(a.grad)

None
tensor([0.7311, 0.8808, 0.9526], grad_fn=<SigmoidBackward0>)
tensor([0.1966, 0.1050, 0.0452])
